#!/usr/bin/env sh

export NVM_DIR="${NVM_DIR:-$HOME/.nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

echo "PATH=$PATH"
which node || echo "node not found"
which pnpm || echo "pnpm not found"

pnpm exec lint-staged